# Generated by Django 3.2.6 on 2021-09-04 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_file', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='name',
            field=models.CharField(default='default', max_length=10),
        ),
    ]
